- README.md
- pom.xml
- src/main/java/org/zalando/baigan/proxy/handler/ContextAwareConfigurationMethodInvocationHandler.java
- src/main/java/org/zalando/baigan/service/AbstractConfigurationRespository.java
- src/main/java/org/zalando/baigan/service/EtcdConfigurationRespositoryImpl.java
- src/main/java/org/zalando/baigan/service/GitCacheLoader.java
- src/main/java/org/zalando/baigan/service/GitConfig.java
- src/main/java/org/zalando/baigan/service/GitConfigurationRespository.java
- src/test/java/org/zalando/baigan/service/GitCacheLoaderTest.java
- src/test/java/org/zalando/baigan/service/GitRepositoryTest.java
Adding support for Git as Configuration Repository.
> Integration through configuration bean

- src/main/java/org/zalando/baigan/service/github/GitCacheLoader.java
- src/test/java/org/zalando/baigan/service/github/GitCacheLoaderTest.java
Reuse of a single thread pool
This closes https://github.com/zalando/baigan-config/issues/13 and requires https://github.com/zalando/baigan-config/pull/12
> Fixed the threading issue

- pom.xml
- src/main/java/org/zalando/baigan/service/S3ConfigurationRepository.java
- src/main/java/org/zalando/baigan/service/aws/S3FileLoader.java
- Added support for AWS KMS transparent decryption of the whole configuration json for sensitive data.
> Added support for AWS KMS transparent decryption

- pom.xml
- src/test/java/org/zalando/baigan/service/github/GitCacheLoaderTest.java
> GH-23 Use build-in MD5 digest function.

- pom.xml
> Preparing next iteration 0.13.0

- .zappr.yaml
Adds `zalando-incubator` to allowed orgs.
> Allow org to approve

- pom.xml
- deployed to nexus
- preparing next iteration
> Release 0.13.0

- pom.xml
> Prepare next iteration

- src/main/java/org/zalando/baigan/service/S3ConfigurationRepository.java
Make `S3ConfigurationRepository` extendable
> Enable interception when the values for an S3 repository are updated

- src/main/java/org/zalando/baigan/service/S3ConfigurationRepository.java
Currently the `ScheduledThreadPoolExecutor` is not shutdown when the application shuts down. This can lead to the behavior that the application failed to start, but doesn't exit with an exit code. Instead it's still running and waiting for the `ScheduledThreadPoolExecutor` to finish it's job which will never happen.
Using `Lifecycle` prevents that as the `S3ConfigurationRepository` now listens to the stop action and shutsdown the `ScheduledThreadPoolExecutor`.
> shutdown executorservice in s3configRepo

- pom.xml
... and preparing the next iteration.
> Release 0.16.0

- src/main/java/org/zalando/baigan/service/S3ConfigurationRepository.java
As discussed, removing the Lifecycle solution and instead supporting the passing of an own executor.
> support passing of own executor

- pom.xml
... and prepare next iteration
> Release 0.17.0

- .github/workflows/build.yaml
- README.md
- circle.yml
Setup Github workflow for building pull requests
> Github Workflow

- .github/workflows/release.yaml
- .gitignore
- pom.xml
- release.sh
* add release workflow
* add release script
> add release workflow

- release.sh
> fix release script

- .github/workflows/build.yaml
- pom.xml
* remove unused dependencies
* run integration-test on build
> Streamline Dependencies

- src/main/java/org/zalando/baigan/service/FileSystemConfigurationRepository.java
- src/main/java/org/zalando/baigan/service/S3ConfigurationRepository.java
Just a few minor code style changes (as marked by violations) to test the pull request and release flow.
> minor code style changes

- README.md
In the context of https://github.com/zalando-stups/baigan-config/pull/72.
> Add note about 0.18.0 + 0.19.0 + 0.19.1 releases

- .github/workflows/build.yaml
ensure that javadoc generates without errors early
> generate javadoc during build

- README.md
See https://github.com/zalando-stups/baigan-config/issues/90
> Updated readme with Java 11

- src/main/java/org/zalando/baigan/proxy/handler/ContextAwareConfigurationMethodInvocationHandler.java
- src/main/java/org/zalando/baigan/repository/ConfigurationParser.java
We are trying to adjust the wording slightly to reduce the chance of confusion, possibly. No quantitative nor qualitative research has happened, it's a shot in the dark.
> clarified log messages on configuration mismatches

- pom.xml
- src/main/java/org/zalando/baigan/repository/aws/S3FileLoader.java
This PR updates failsafe library to the latest version.
> Update failsafe version

- pom.xml
Just as https://github.com/zalando-incubator/baigan-config/pull/119 for Spring 6 :eye:
> Bump Spring 5

- pom.xml
See https://central.sonatype.org/faq/what-is-different-between-central-portal-and-legacy-ossrh/
> Publish to Central Portal
